name: Stock Tracker CI

on:
  push:
    branches:
      - main  # Change this to your main branch name
  pull_request:
    branches:
      - main  # Change this to your main branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x  # Change this to your desired Python version

      - name: Install dependencies
        run: pip install pandas gspread gspread_dataframe oauth2client google-api-python-client tqdm openpyxl

      - name: Run Python code
        run: python AdsSpent.py
